"use client";
import { useState } from "react";
import Link from "next/link";
import { Clock, RotateCcw } from "lucide-react";
import { AppNav } from "@/components/facefit/AppNav";
import { ApplicationInfoCard } from "@/components/facefit/onboarding/ApplicationInfoCard";
import { JobPostingCard } from "@/components/facefit/onboarding/JobPostingCard";
import { InterviewerSelectCard } from "@/components/facefit/onboarding/InterviewerSelectCard";
import { IntensitySummaryRow } from "@/components/facefit/onboarding/IntensitySummaryRow";
const names:Record<string,string>={technical:"기술 면접관",hr:"HR 면접관",executive:"경영진 면접관"};
export default function OnboardingPage(){const [interviewer,setInterviewer]=useState("technical");const [cancel,setCancel]=useState(false);return <div className="flex min-h-screen flex-col bg-ivory-50"><AppNav active="새 면접"/><main className="mx-auto w-full max-w-[1200px] flex-1 px-6 py-10 md:px-10"><div className="mb-8 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-[-.01em] text-ink-900">새 면접 설정</h1><p className="mt-2 text-sm text-ink-600">지원 정보와 면접 조건을 한 번에 설정해 주세요.</p></div><button onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} className="flex items-center gap-2 rounded-lg border border-line-300 bg-white px-4 py-2.5 text-[13px] font-semibold text-ink-700"><RotateCcw size={14}/>입력 내용 다시 보기</button></div><div className="flex flex-col gap-5"><div className="grid gap-5 lg:grid-cols-2"><ApplicationInfoCard/><JobPostingCard/></div><InterviewerSelectCard onSelect={setInterviewer}/><IntensitySummaryRow interviewer={names[interviewer]}/></div><div className="mt-8 flex flex-wrap items-center justify-between gap-4 border-t border-line-200 pt-6"><button onClick={()=>setCancel(true)} className="rounded-lg border border-line-300 bg-white px-6 py-3 text-sm font-semibold text-ink-700">취소</button><div className="flex items-center gap-4"><span className="flex items-center gap-1.5 text-xs text-ink-400"><Clock size={13}/>예상 소요 시간 15~20분</span><Link href="/equipment" className="inline-flex items-center gap-2 rounded-lg bg-sunset-600 px-7 py-3 text-sm font-semibold text-white">면접 시작하기</Link></div></div></main>{cancel&&<div className="fixed inset-0 z-50 grid place-items-center bg-ink-900/30 p-4"><section role="dialog" aria-modal="true" className="w-full max-w-md rounded-[18px] bg-white p-6"><h2 className="text-xl font-bold">설정을 취소할까요?</h2><p className="mt-2 text-sm leading-6 text-ink-600">입력한 지원 정보와 면접 조건은 저장되지 않습니다.</p><div className="mt-6 flex justify-end gap-2"><button onClick={()=>setCancel(false)} className="rounded-lg bg-moss-900 px-4 py-3 text-sm font-bold text-white">계속 설정하기</button><Link href="/" className="rounded-lg border border-line-300 px-4 py-3 text-sm font-bold text-ink-700">취소하고 나가기</Link></div></section></div>}</div>}
