"use client";

import { AlertCircle, Check, FileText, Mic, RefreshCw, ShieldAlert, Upload, Video } from "lucide-react";
import { ReactNode, useEffect, useRef, useState } from "react";
import { cn } from "@/lib/utils";
import { errorGuidance } from "@/lib/facefit-content";

export function StatusBadge({ children, tone = "green" }: { children: ReactNode; tone?: "green" | "orange" | "muted" }) { const styles = { green: "bg-moss-300/35 text-moss-900", orange: "bg-sunset-300/25 text-sunset-700", muted: "bg-ivory-300 text-ink-600" }; return <span className={cn("inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold", styles[tone])}><span className="size-1.5 rounded-full bg-current" />{children}</span>; }

export function PermissionState({ kind = "camera" }: { kind?: "camera" | "microphone" | "device" }) { const [message,setMessage]=useState(""); const isDevice=kind==="device"; const title=isDevice?"연결된 장치를 찾을 수 없어요.":kind==="microphone"?"마이크 사용 권한이 필요합니다.":"카메라 사용 권한이 필요합니다."; const description=isDevice?errorGuidance.device:errorGuidance.permission; const Icon=isDevice?ShieldAlert:kind==="microphone"?Mic:Video; return <section className="rounded-2xl border border-line-200 bg-white p-6 text-center" role="alert"><Icon className="mx-auto mb-3 text-sunset-700" size={27}/><h2 className="text-lg font-bold text-ink-900">{title}</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-ink-600">{description}</p><div className="mt-5 flex flex-wrap justify-center gap-2"><button onClick={()=>setMessage("장치 상태를 다시 확인했어요. 실제 권한 요청은 연결 전입니다.")} className="rounded-lg bg-moss-900 px-4 py-2.5 text-sm font-semibold text-white">다시 확인</button><button onClick={()=>setMessage("주소창의 자물쇠 아이콘에서 카메라와 마이크를 허용해 주세요.")} className="rounded-lg border border-line-300 px-4 py-2.5 text-sm font-semibold text-ink-700">설정 방법 보기</button></div>{message&&<p role="status" className="mt-4 rounded-lg bg-ivory-100 p-3 text-xs leading-5 text-ink-700">{message}</p>}</section>; }

export function EmptyState({ variant = "records" }: { variant?: "records" | "search" | "growth" }) { const copy = variant === "records" ? ["아직 완료한 면접이 없어요.", "첫 면접을 시작하면 기록과 성장 변화를 이곳에서 확인할 수 있습니다."] : variant === "search" ? ["조건에 맞는 기록이 없어요.", "필터를 조정하거나 다른 검색어를 입력해 보세요."] : ["성장 분석을 위한 데이터가 부족해요.", "면접을 2회 이상 완료하면 변화 추이를 확인할 수 있습니다."]; return <section className="border-y border-line-200 py-16 text-center"><div className="mx-auto grid size-12 place-items-center rounded-xl border border-moss-300 bg-ivory-100 text-moss-700"><FileText size={22} /></div><h2 className="mt-5 text-xl font-bold text-ink-900">{copy[0]}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-ink-600">{copy[1]}</p>{variant === "records" && <a href="/onboarding" className="mt-6 inline-flex rounded-lg bg-sunset-600 px-5 py-3 text-sm font-bold text-white">첫 면접 시작하기</a>}</section>; }

export function ErrorState({ title = "일시적인 오류가 발생했어요." }: { title?: string }) { const [retried,setRetried]=useState(false); return <section className="rounded-2xl border border-sunset-300 bg-[#fff9f5] p-6 text-center" role="alert"><AlertCircle className="mx-auto text-sunset-700" /><h2 className="mt-3 text-lg font-bold text-ink-900">{title}</h2><p className="mt-2 text-sm text-ink-600">잠시 후 다시 시도하거나 이전 화면으로 돌아가 주세요.</p><button onClick={()=>setRetried(true)} className="mt-5 inline-flex items-center gap-2 rounded-lg border border-line-300 bg-white px-4 py-2.5 text-sm font-semibold text-ink-700"><RefreshCw size={15}/>다시 시도</button>{retried&&<p role="status" className="mt-3 text-xs font-semibold text-moss-700">다시 시도를 요청했어요.</p>}</section>; }
export function Skeleton({ className }: { className?: string }) { return <div aria-hidden="true" className={cn("animate-pulse rounded-lg bg-ivory-300", className)} />; }
export function FileUploader() { const [status,setStatus] = useState<"default" | "uploading" | "analyzing" | "success" | "failed">("default"); if (status === "success") return <div className="rounded-xl border border-moss-300 bg-[#F6FAF5] p-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-moss-700 text-white"><FileText size={17}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-ink-900">job-posting.pdf</p><p className="text-xs text-ink-600">1.2 MB · 업로드 완료</p></div><Check className="text-moss-700" size={19}/></div><div className="mt-3 flex gap-3 border-t border-moss-300 pt-3"><button onClick={()=>setStatus("default")} className="text-xs font-bold text-moss-700">변경</button><button onClick={()=>setStatus("default")} className="text-xs font-bold text-ink-600">삭제</button></div></div>; if (status === "failed") return <div className="rounded-xl border border-sunset-300 bg-[#fff9f5] p-5 text-center"><AlertCircle className="mx-auto text-sunset-700" size={21}/><p className="mt-2 text-sm font-bold">파일 형식을 확인해 주세요.</p><p className="mt-1 text-xs text-ink-600">PDF, DOCX 파일만 업로드할 수 있어요.</p><div className="mt-3 flex justify-center gap-3"><button onClick={()=>setStatus("uploading")} className="text-xs font-bold text-moss-700">다시 시도</button><button onClick={()=>setStatus("default")} className="text-xs font-bold text-ink-600">다른 파일 선택</button></div></div>; if (status === "uploading" || status === "analyzing") return <div className="rounded-xl border border-line-300 bg-ivory-100 p-5"><div className="flex items-center justify-between text-sm"><span className="font-bold text-ink-900">{status === "uploading" ? "파일을 업로드하고 있어요" : "문서를 분석하고 있어요"}</span><span className="text-moss-700">처리 중</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-line-200"><span className="block h-full w-2/3 animate-pulse rounded-full bg-moss-700"/></div><button onClick={()=>setStatus(status === "uploading" ? "analyzing" : "success")} className="mt-4 text-xs font-bold text-moss-700">다음 상태 보기</button></div>; return <div className="rounded-xl border border-dashed border-line-300 bg-ivory-100 p-5 text-center"><Upload className="mx-auto text-moss-700" size={22}/><p className="mt-2 text-sm font-semibold text-ink-900">파일을 끌어 놓거나 선택해 주세요</p><p className="mt-1 text-xs text-ink-600">PDF, DOCX · 최대 10MB</p><div className="mt-4 flex justify-center gap-3"><button onClick={()=>setStatus("uploading")} className="rounded-lg border border-line-300 bg-white px-4 py-2 text-sm font-semibold text-ink-700">파일 선택</button><button onClick={()=>setStatus("failed")} className="text-xs font-semibold text-ink-600">실패 상태</button></div></div>; }
export function ConfirmModal({ open, onClose }: { open: boolean; onClose: () => void }) { const closeRef = useRef<HTMLButtonElement>(null); useEffect(() => { if (open) closeRef.current?.focus(); }, [open]); useEffect(() => { const escape = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", escape); return () => window.removeEventListener("keydown", escape); }, [onClose]); if (!open) return null; return <div className="fixed inset-0 z-50 grid place-items-center bg-ink-900/35 p-4"><section role="dialog" aria-modal="true" aria-labelledby="end-title" className="w-full max-w-md rounded-[18px] border border-line-200 bg-white p-6 shadow-xl"><div className="flex items-start justify-between gap-3"><div><h2 id="end-title" className="text-xl font-bold text-ink-900">면접을 종료할까요?</h2><p className="mt-2 text-sm leading-6 text-ink-600">현재까지의 답변은 저장되며, 종료 후 분석 리포트를 생성합니다.</p></div><button ref={closeRef} onClick={onClose} aria-label="모달 닫기" className="text-ink-600">×</button></div><dl className="mt-5 grid grid-cols-3 gap-2 rounded-xl bg-ivory-100 p-3 text-center"><div><dt className="text-xs text-ink-600">경과 시간</dt><dd className="mt-1 text-sm font-bold">12:38</dd></div><div><dt className="text-xs text-ink-600">완료 질문</dt><dd className="mt-1 text-sm font-bold">4 / 5</dd></div><div><dt className="text-xs text-ink-600">저장 상태</dt><dd className="mt-1 text-sm font-bold text-moss-700">완료</dd></div></dl><div className="mt-6 flex flex-col gap-2 sm:flex-row sm:justify-end"><button onClick={onClose} className="rounded-lg bg-moss-900 px-4 py-3 text-sm font-semibold text-white">면접 계속하기</button><a href="/analysis" className="rounded-lg border border-sunset-600 px-4 py-3 text-center text-sm font-semibold text-sunset-700">종료하고 분석하기</a></div></section></div>; }
export function Toast({ message = "변경 사항을 저장했어요." }: { message?: string }) { return <div role="status" className="fixed right-5 bottom-5 z-40 flex items-center gap-2 rounded-xl bg-ink-900 px-4 py-3 text-sm font-medium text-white shadow-lg"><Check size={16} />{message}</div>; }
