import { Pause, Play } from "lucide-react";
import { useState } from "react";
import { AppNav } from "@/components/facefit/AppNav";
import { PageContainer } from "@/components/facefit/layout/PageContainer";

const axes = [{ label: "시선 접촉", score: 80, note: "카메라 응시 58%, 권장 75%", chip: "정면 응시 훈련 필요" }, { label: "발화 안정", score: 70, note: "필러 14회", chip: "문장 끝까지 말하기" }, { label: "자세", score: 75, note: "상체 흔들림 5회 감지", chip: "어깨 고정 연습" }, { label: "답변 내용", score: 88, note: "구조화된 STAR 답변 4/5", chip: "우수" }];

export default function ReportPage() {
  const [tab, setTab] = useState("종합 리포트");
  const [playing, setPlaying] = useState(false);
  return <div className="min-h-screen bg-[#f8f6ff] text-[#17121e]"><AppNav active="마이페이지" />
    <PageContainer as="main" size="wide" className="py-10">
      <p className="text-xs text-[#948aa3]">응시 2026.07.10 10:24 · 압박형 모의면접</p>
      <h1 className="mt-3 text-3xl font-bold tracking-[-.055em]">민준님은 <span className="text-[#5831b9]">답변 내용</span>이 탁월한 지원자입니다.</h1>
      <p className="mt-2 text-sm text-[#948aa3]">AI/개발자 · 압박형 페르소나 · 5문항</p>
      <div className="mt-6 flex gap-7 border-b border-[#e6dfef]" role="tablist">{["종합 리포트", "질문별 피드백", "합격 가이드"].map((item) => <button key={item} onClick={() => setTab(item)} className={tab === item ? "border-b-2 border-[#17121e] pb-3 text-sm font-bold" : "pb-3 text-sm text-[#948aa3]"}>{item}</button>)}</div>
      <section className="mt-6 rounded-[20px] bg-[#5227af] px-7 py-8 text-white md:flex md:items-center md:gap-9 md:px-11">
        <div className="grid size-28 shrink-0 place-items-center rounded-full border-[8px] border-white text-center"><strong className="text-4xl leading-none">85<small className="text-sm">점</small></strong><span className="text-xs text-white/70">종합 분석 점수</span></div>
        <div className="mt-5 max-w-4xl md:mt-0"><div className="flex items-center gap-2 text-sm text-white/70"><b>총평</b><span className="rounded-full bg-white/15 px-2 py-0.5 text-xs">샘플 리포트</span></div><p className="mt-3 text-lg font-semibold leading-8">답변이 구조적이고 사례가 명확해 설득력이 돋보였습니다. 목소리 톤은 안정적이었으나, 시선 처리에서 약간의 긴장감이 관찰됐습니다. 압박 질문 상황에서도 침착하게 논리를 유지한 점이 이번 면접의 강점입니다.</p></div>
      </section>
      {tab === "종합 리포트" ? <><section className="mt-7 grid gap-4 md:grid-cols-3">{[["Q1 · 자기소개", 82], ["Q2 · 프로젝트 경험", 69], ["Q3 · 꼬리질문", 74]].map(([title, score]) => <article key={String(title)} className="rounded-2xl border border-[#e5dfeb] bg-white px-6 py-5"><p className="text-sm font-semibold text-[#877d91]">{title}</p><strong className="mt-6 block text-sm">{score}</strong><div className="mt-2 h-16 w-9 rounded-md bg-[linear-gradient(180deg,#864cf2,#5420ad)]" /><p className="mt-1 text-xs">내 점수</p></article>)}</section>
        <section className="mt-6 grid gap-8 rounded-[20px] border border-[#e5dfeb] bg-white p-7 lg:grid-cols-[280px_1fr] lg:items-center"><Radar /><div className="space-y-3">{axes.map((axis, index) => <div key={axis.label} className="flex items-center justify-between gap-4 rounded-xl border border-[#e3ddec] bg-[#faf8ff] px-5 py-4"><div><b className="text-sm">{axis.label}: {axis.score}/100</b><p className="mt-1 text-xs text-[#948aa3]">근거: {axis.note}</p></div><span className={index === 1 ? "rounded-full bg-[#e4faef] px-3 py-1 text-xs font-bold text-[#168750]" : index === 2 ? "rounded-full bg-[#fff1e8] px-3 py-1 text-xs font-bold text-[#df672f]" : "rounded-full bg-[#f2eaff] px-3 py-1 text-xs font-bold text-[#6d35d0]"}>{axis.chip}</span></div>)}</div></section>
        <section className="mt-6 rounded-[20px] border border-[#e5dfeb] bg-white p-7"><h2 className="font-bold">축별 점수</h2><div className="mt-5 space-y-4">{axes.map((axis) => <div key={axis.label}><div className="flex justify-between text-sm text-[#887d94]"><span>{axis.label}</span><span>{axis.score}</span></div><div className="mt-2 h-2 rounded-full bg-[#e9e4ef]"><div className="h-full rounded-full bg-[linear-gradient(90deg,#7c40ee,#05ae95)]" style={{ width: `${axis.score}%` }} /></div></div>)}</div></section>
        <section className="mt-6 grid gap-5 md:grid-cols-2"><article className="rounded-[20px] border border-[#e5dfeb] bg-white p-7"><p className="text-sm font-bold text-[#315e46]">● 내 목소리로 듣기 · BETA</p><h2 className="mt-3 text-xl font-bold">개선 답변, 표준 음성으로 들어보세요</h2><p className="mt-2 text-sm text-[#948aa3]">개선 답변을 음성으로 들으며 다시 연습해보세요.</p><button onClick={() => setPlaying(!playing)} className="mt-5 flex w-full items-center gap-3 rounded-full border border-[#e5dfeb] bg-[#faf8ff] px-4 py-3"><span className="grid size-8 place-items-center rounded-full bg-[#315e46] text-white">{playing ? <Pause size={15} /> : <Play size={15} fill="currentColor" />}</span><span className="h-1 flex-1 rounded-full bg-[#dcd5e6]"><i className="block h-full w-[32%] rounded-full bg-[#6d8b77]" /></span><span className="text-xs text-[#948aa3]">0:14 / 0:44</span></button></article><article className="rounded-[20px] border border-[#e5dfeb] bg-white p-7"><p className="text-sm font-bold text-[#df672f]">■ 마무리 답변 추천</p><h2 className="mt-3 text-xl font-bold">마지막으로 하고싶은 말, AI가 추천해요</h2><div className="mt-4 space-y-2 text-sm"><p className="rounded-xl border border-[#e5dfeb] p-3">“오늘 논의된 프로젝트 경험을 바탕으로, 입사 후에도 데이터 기반 문제 해결로 빠르게 기여하고 싶습니다.”</p><p className="rounded-xl border border-[#e5dfeb] p-3">“부족한 점은 빠르게 배우는 태도로 채워왔습니다.”</p></div></article></section></> : <section className="mt-8 rounded-2xl border border-[#e5dfeb] bg-white p-8 text-center text-[#948aa3]">{tab} 화면은 리포트의 다음 단계에서 제공됩니다.</section>}
    </PageContainer></div>;
}

function Radar() { return <div className="mx-auto aspect-square w-full max-w-[255px]"><svg viewBox="0 0 260 260" className="h-full w-full" aria-label="4축 평가 레이더"><defs><linearGradient id="radar" x1="0" x2="1"><stop stopColor="#a876ff" stopOpacity=".35"/><stop offset="1" stopColor="#3ed5c0" stopOpacity=".4"/></linearGradient></defs>{[35, 65, 95].map((r) => <polygon key={r} points={`130,${130-r} ${130+r},130 130,${130+r} ${130-r},130`} fill="none" stroke="#ded4f0" />)}<line x1="130" y1="35" x2="130" y2="225" stroke="#ded4f0"/><line x1="35" y1="130" x2="225" y2="130" stroke="#ded4f0"/><polygon points="130,45 209,130 130,206 46,130" fill="url(#radar)" stroke="#905df9" strokeWidth="3"/>{[[130,45],[209,130],[130,206],[46,130]].map(([x,y]) => <circle key={`${x}${y}`} cx={x} cy={y} r="4" fill="#905df9"/>)}<text x="130" y="18" textAnchor="middle" fontSize="12">시선 접촉</text><text x="245" y="134" textAnchor="end" fontSize="12">발화</text><text x="130" y="250" textAnchor="middle" fontSize="12">자세</text><text x="15" y="134" fontSize="12">답변 내용</text></svg></div>; }
