import { Link } from "react-router-dom";
import { Check, ChevronLeft, CircleAlert, Mic, Pause, Play, RefreshCw, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { AppNav } from "@/components/facefit/AppNav";
import { PageContainer } from "@/components/facefit/layout/PageContainer";

type Step = "guide" | "recording" | "review" | "creating" | "ready" | "failed";
const readScript = "안녕하세요. 저는 새로운 문제를 구조적으로 이해하고, 팀과 함께 더 나은 방법을 찾는 일을 좋아합니다. 오늘 면접에서는 제 경험을 명확하고 편안하게 말씀드리겠습니다.";

export default function VoiceProfilePage() {
  const [step, setStep] = useState<Step>("guide");
  const [seconds, setSeconds] = useState(0);
  useEffect(() => { if (step !== "recording") return; const id = window.setInterval(() => setSeconds((value) => Math.min(value + 1, 45)), 1000); return () => window.clearInterval(id); }, [step]);
  useEffect(() => { if (step !== "creating") return; const id = window.setTimeout(() => setStep("ready"), 1700); return () => window.clearTimeout(id); }, [step]);
  const stateIndex = ["guide", "recording", "review", "creating", "ready"].indexOf(step);
  return <div className="min-h-screen bg-[#f7f5ef] text-ink-900"><AppNav active="새 면접" />
    <PageContainer as="main" size="compact" className="py-8 md:py-12"><Link to="/equipment" className="inline-flex items-center gap-1.5 text-sm font-semibold text-ink-600 hover:text-moss-900"><ChevronLeft size={16}/>장비 확인으로</Link>
      <header className="mt-7 text-center"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-[#ecf2ed] text-moss-900"><Sparkles size={22}/></span><h1 className="mt-5 text-3xl font-bold tracking-[-.055em]">내 음성으로 개선 답변을 들어보세요</h1><p className="mt-3 text-sm leading-6 text-ink-600">약 45초 동안 안내 문장을 읽으면, 리포트의 개선 답변을 내 목소리에 가깝게 들을 수 있어요.</p></header>
      <ol className="mx-auto mt-8 flex max-w-[600px] justify-between text-center text-xs"><Step label="안내" active={stateIndex >= 0} done={stateIndex > 0}/><Step label="녹음" active={stateIndex >= 1} done={stateIndex > 1}/><Step label="확인" active={stateIndex >= 2} done={stateIndex > 2}/><Step label="준비 완료" active={stateIndex >= 3} done={stateIndex > 3}/></ol>
      <section className="mt-8 rounded-2xl border border-line-300 bg-white p-6 shadow-[0_16px_34px_rgba(50,55,45,.06)] md:p-8">
        {step === "guide" && <div><Guide onStart={() => { setSeconds(0); setStep("recording"); }} /><Link to="/session/live" className="mt-3 inline-flex min-h-11 w-full items-center justify-center rounded-xl border border-line-300 px-5 py-3 text-sm font-bold text-ink-700 transition hover:bg-ivory-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-moss-700">건너뛰기</Link>{/* TODO: Persist an explicit skipped voice-profile state when the API is connected. */}</div>}
        {step === "recording" && <Recording seconds={seconds} onStop={() => setStep("review")} />}
        {step === "review" && <Review onAgain={() => { setSeconds(0); setStep("recording"); }} onUse={() => setStep("creating")} />}
        {step === "creating" && <Creating />}
        {step === "ready" && <Ready onRetry={() => setStep("guide")} />}
        {step === "failed" && <Failure onRetry={() => setStep("guide")} />}
      </section>
      <p className="mt-5 flex items-center justify-center gap-2 text-xs text-ink-400"><ShieldCheck size={14}/>이 화면은 프론트엔드 데모입니다. 실제 음성 저장 또는 복제는 수행하지 않아요.</p>
    </PageContainer>
  </div>;
}
function Step({ label, active, done }: { label:string; active:boolean; done:boolean }) { return <li className="relative flex flex-1 flex-col items-center gap-2 after:absolute after:left-[60%] after:top-3 after:h-px after:w-[80%] after:bg-line-300 last:after:hidden"><span className={active ? "grid size-6 place-items-center rounded-full bg-moss-900 text-white" : "grid size-6 place-items-center rounded-full bg-ivory-300 text-ink-400"}>{done ? <Check size={13}/> : ""}</span><span className={active ? "font-bold text-moss-900" : "text-ink-400"}>{label}</span></li>; }
function Guide({onStart}:{onStart:()=>void}) { return <div className="mx-auto max-w-[620px]"><p className="text-sm font-bold text-moss-900">녹음 전 확인</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{["조용한 곳에서 진행해 주세요.", "입과 마이크 사이를 15~20cm로 유지해요.", "평소 말하듯 또렷하게 읽어 주세요.", "언제든 다시 녹음할 수 있어요."].map(text=><p key={text} className="flex items-center gap-2 rounded-xl bg-[#f6f8f5] px-4 py-3 text-sm"><Check size={16} className="text-moss-700"/>{text}</p>)}</div><p className="mt-6 rounded-xl border border-line-200 bg-ivory-100 p-5 text-base leading-8 text-ink-700">“{readScript}”</p><button onClick={onStart} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-moss-900 px-5 py-4 text-sm font-bold text-white"><Mic size={17}/>녹음 시작하기</button></div>; }
function Recording({seconds,onStop}:{seconds:number;onStop:()=>void}) { return <div className="mx-auto max-w-[620px] text-center"><span className="mx-auto grid size-16 place-items-center rounded-full bg-[#fff1e8] text-sunset-700"><Mic size={28}/></span><h2 className="mt-5 text-xl font-bold">안내 문장을 읽어 주세요</h2><p className="mt-2 text-sm text-ink-600">평소 대화하듯 자연스럽게 말하면 됩니다.</p><p className="mt-6 rounded-xl border border-line-200 bg-ivory-100 p-5 text-left text-base leading-8 text-ink-700">“{readScript}”</p><div className="mt-6 flex items-center justify-center gap-4"><Wave active/><strong className="text-xl tabular-nums">00:{String(seconds).padStart(2,"0")}</strong><span className="text-sm text-ink-400">/ 00:45</span></div><button onClick={onStop} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-sunset-600 px-5 py-3 text-sm font-bold text-white"><Pause size={16}/>녹음 마치기</button></div>; }
function Review({onAgain,onUse}:{onAgain:()=>void;onUse:()=>void}) { const [playing,setPlaying]=useState(false); return <div className="mx-auto max-w-[620px] text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-[#ecf2ed] text-moss-900"><Check size={27}/></span><h2 className="mt-5 text-xl font-bold">녹음이 잘 되었어요</h2><p className="mt-2 text-sm text-ink-600">목소리와 말하기 속도를 한 번 확인해 보세요.</p><button onClick={()=>setPlaying(!playing)} className="mt-6 flex w-full items-center gap-4 rounded-xl border border-line-300 bg-ivory-100 p-4 text-left"><span className="grid size-10 place-items-center rounded-full bg-moss-900 text-white">{playing?<Pause size={16}/>:<Play size={16} fill="currentColor"/>}</span><Wave active={playing}/><span className="text-xs text-ink-600">00:00 / 00:45</span></button><div className="mt-6 flex gap-3"><button onClick={onAgain} className="flex-1 rounded-xl border border-line-300 py-3 text-sm font-bold">다시 녹음</button><button onClick={onUse} className="flex-1 rounded-xl bg-moss-900 py-3 text-sm font-bold text-white">이 녹음 사용하기</button></div></div>; }
function Creating() { return <div className="py-10 text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-[#ecf2ed] text-moss-900"><RefreshCw className="animate-spin" size={25}/></span><h2 className="mt-5 text-xl font-bold">음성 프로필을 준비하고 있어요</h2><p className="mt-2 text-sm text-ink-600">잠시 후 개선 답변을 내 목소리로 들을 수 있어요.</p><div className="mx-auto mt-7 h-1.5 max-w-sm overflow-hidden rounded-full bg-line-200"><i className="block h-full w-2/3 animate-pulse rounded-full bg-moss-700"/></div></div>; }
function Ready({onRetry}:{onRetry:()=>void}) { return <div className="py-7 text-center"><span className="mx-auto grid size-16 place-items-center rounded-full bg-moss-900 text-white"><Check size={29}/></span><h2 className="mt-5 text-xl font-bold">내 음성 프로필 준비 완료</h2><p className="mt-2 text-sm text-ink-600">이제 면접 리포트의 개선 답변을 내 목소리에 가깝게 들을 수 있어요.</p><div className="mt-7 flex justify-center gap-3"><Link to="/report" className="rounded-xl bg-sunset-600 px-5 py-3 text-sm font-bold text-white">리포트에서 들어보기</Link><button onClick={onRetry} className="rounded-xl border border-line-300 px-5 py-3 text-sm font-bold">다시 녹음</button></div></div>; }
function Failure({onRetry}:{onRetry:()=>void}) { return <div className="py-7 text-center"><CircleAlert className="mx-auto text-sunset-700" size={34}/><h2 className="mt-4 text-xl font-bold">녹음을 확인하지 못했어요</h2><p className="mt-2 text-sm text-ink-600">마이크 연결을 확인하고, 조용한 곳에서 다시 시도해 주세요.</p><button onClick={onRetry} className="mt-6 rounded-xl border border-line-300 px-5 py-3 text-sm font-bold">다시 시도</button></div>; }
function Wave({active=false}:{active?:boolean}) { return <span className="flex flex-1 items-center justify-center gap-1">{[12,18,26,14,35,22,40,18,28,14,32,20,12].map((height,index)=><i key={index} className={active?"w-1 rounded-full bg-moss-700 animate-pulse":"w-1 rounded-full bg-ink-300"} style={{height,animationDelay:`${index*55}ms`}}/>)}</span>; }
