"""Validate Stage 18 result files without exposing either result to the other."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app.vision.pilot_annotation_package import (
    PARTICIPANT_ID,
    RATER_IDS,
    SESSION_ID,
    annotation_readiness_status,
    cross_rater_similarity_warnings,
    registry_from_dict,
    validate_rater_submission,
)
from app.vision.pilot_video_intake import (
    assert_no_forbidden_semantics,
    load_strict_json,
    sha256_file,
    write_strict_json,
)


def _validate(
    path: Path,
    *,
    rater_id: str,
    answers: list[dict],
    registry,
) -> tuple[dict, dict | None]:
    common = {
        "participant_id": PARTICIPANT_ID,
        "session_id": SESSION_ID,
        "rater_id": rater_id,
        "expected_result_file": path.name,
    }
    if not path.exists():
        return ({
            **common,
            "result_file_exists": False,
            "validation_status": "NOT_SUBMITTED",
            "valid": None,
            "event_count": None,
            "errors": [],
            "warnings": [],
        }, None)
    try:
        value = load_strict_json(path)
        details = validate_rater_submission(
            value,
            expected_rater_id=rater_id,
            answers=answers,
            registry=registry,
        )
    except ValueError as exc:
        return ({
            **common,
            "result_file_exists": True,
            "result_sha256": sha256_file(path),
            "validation_status": "FAILED",
            "valid": False,
            "event_count": None,
            "errors": [str(exc)],
            "warnings": [],
        }, None)
    return ({
        **common,
        "result_file_exists": True,
        "result_sha256": sha256_file(path),
        "validation_status": "PASSED",
        "valid": True,
        "event_count": details["event_count"],
        "errors": [],
        "warnings": [],
    }, value)


def _markdown(report: dict) -> str:
    return (
        "# Face-Fit Stage 18 Validation Report\n\n"
        f"- Participant: `{report['participant_id']}`\n"
        f"- Session: `{report['session_id']}`\n"
        f"- Rubric: `{report['rubric_id']} {report['rubric_version']}`\n"
        f"- Included labels: `{report['label_count']}`\n"
        f"- Included Answer intervals: `{report['answer_count']}`\n"
        f"- Rater A result: `{report['rater_results']['RATER_A']}`\n"
        f"- Rater B result: `{report['rater_results']['RATER_B']}`\n"
        f"- Current status: `{report['current_status']}`\n\n"
        "No Annotation Events were generated by this validator. Similarity "
        "warnings are informational only. Agreement and Kappa were not "
        "calculated, and the dataset remains unfrozen.\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--package-dir", type=Path, required=True)
    parser.add_argument("--metadata", type=Path, required=True)
    parser.add_argument("--registry", type=Path, required=True)
    args = parser.parse_args()
    package_dir = args.package_dir.resolve()
    manifest = load_strict_json(
        package_dir / "annotation_package_manifest.json"
    )
    if (
        manifest["participant_id"] != PARTICIPANT_ID
        or manifest["session_id"] != SESSION_ID
    ):
        raise ValueError("annotation package reference mismatch")
    metadata = load_strict_json(args.metadata.resolve())
    registry = registry_from_dict(
        load_strict_json(args.registry.resolve())
    )
    validations = {}
    submissions = {}
    for rater_id, directory in zip(RATER_IDS, ("rater_a", "rater_b")):
        validation, submission = _validate(
            package_dir / directory / "annotation_events.json",
            rater_id=rater_id,
            answers=metadata["answers"],
            registry=registry,
        )
        validations[rater_id] = validation
        submissions[rater_id] = submission
    warnings = []
    if all(submissions.values()):
        warnings = cross_rater_similarity_warnings(
            submissions["RATER_A"], submissions["RATER_B"]
        )
    for validation in validations.values():
        validation["warnings"] = list(warnings)
    current_status = annotation_readiness_status(
        validations["RATER_A"], validations["RATER_B"]
    )
    status = {
        "participant_id": PARTICIPANT_ID,
        "session_id": SESSION_ID,
        "rater_a_result_file_exists":
            validations["RATER_A"]["result_file_exists"],
        "rater_b_result_file_exists":
            validations["RATER_B"]["result_file_exists"],
        "current_status": current_status,
        "cross_rater_warnings": warnings,
        "agreement_calculated": False,
        "kappa_calculated": False,
        "dataset_frozen": False,
    }
    report = {
        "schema_version": "1.0.0",
        "stage": 18,
        "participant_id": PARTICIPANT_ID,
        "session_id": SESSION_ID,
        "rubric_id": manifest["rubric_id"],
        "rubric_version": manifest["rubric_version"],
        "label_count": manifest["label_count"],
        "answer_count": manifest["answer_count"],
        "rater_packages_separate": True,
        "blind_contract_valid": True,
        "template_event_count": {"RATER_A": 0, "RATER_B": 0},
        "rater_results": {
            key: value["validation_status"]
            for key, value in validations.items()
        },
        "current_status": current_status,
        "cross_rater_warnings": warnings,
        "actual_annotation_events_generated": False,
        "model_derived_labels_generated": False,
        "agreement_calculated": False,
        "kappa_calculated": False,
        "evaluative_value_produced": False,
        "evaluation_boundary_produced": False,
        "psychological_inference_produced": False,
        "ml_training_performed": False,
        "dataset_frozen": False,
        "dependency_changed": False,
    }
    for value in (*validations.values(), status, report):
        assert_no_forbidden_semantics(value)
    write_strict_json(
        package_dir / "rater_a_validation.json",
        validations["RATER_A"],
    )
    write_strict_json(
        package_dir / "rater_b_validation.json",
        validations["RATER_B"],
    )
    write_strict_json(
        package_dir / "annotation_readiness_status.json", status
    )
    write_strict_json(package_dir / "validation_report.json", report)
    (package_dir / "validation_report.md").write_text(
        _markdown(report), encoding="utf-8"
    )
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
